apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx
spec:
  host: nginx
  subsets:
    - name: blue
      labels:
        slot: blue
    - name: green
      labels:
        slot: green